// <auto-generated />
namespace EasyFast.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170307_Add_Entites : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170307_Add_Entites));
        
        string IMigrationMetadata.Id
        {
            get { return "201703070953070_20170307_Add_Entites"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
