// <auto-generated />
namespace EasyFast.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170308_update_column_修改主键为栏目标识 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170308_update_column_修改主键为栏目标识));
        
        string IMigrationMetadata.Id
        {
            get { return "201703080736152_20170308_update_column_修改主键为栏目标识"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
