"use strict";var userAgent=navigator.userAgent.toLowerCase(),initialDate=new Date(),$document=$(document),$window=$(window),$html=$("html"),isDesktop=$html.hasClass("desktop"),isIE=userAgent.indexOf("msie")!=-1?parseInt(userAgent.split("msie")[1]):userAgent.indexOf("trident")!=-1?11:userAgent.indexOf("edge")!=-1?12:false,isMobile=/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent),isTouch="ontouchstart"in window,perspectiveMenu=$('#perspective'),plugins={pointerEvents:isIE<11?"js/pointer-events.min.js":false,bootstrapTooltip:$("[data-toggle='tooltip']"),bootstrapModalDialog:$('.modal'),bootstrapTabs:$(".tabs"),rdNavbar:$(".rd-navbar"),rdParallax:$(".rd-parallax"),rdGoogleMaps:$(".rd-google-map"),rdMailForm:$(".rd-mailform"),rdInputLabel:$(".form-label"),regula:$("[data-constraints]"),owl:$(".owl-carousel"),statefulButton:$('.btn-stateful'),isotope:$(".isotope"),popover:$('[data-toggle="popover"]'),viewAnimate:$('.view-animate'),photoSwipeGallery:$("[data-photo-swipe-item]"),radio:$("input[type='radio']"),checkbox:$("input[type='checkbox']"),customToggle:$("[data-custom-toggle]"),counter:$(".counter"),progressBar:$(".progress-bar-js"),selectFilter:$("select"),slick:$('.slick-slider'),stepper:$("input[type='number']"),materialTabs:$('.rd-material-tabs')};$document.ready(function(){function isScrolledIntoView(elem){var $window=$(window);return elem.offset().top+ elem.outerHeight()>=$window.scrollTop()&&elem.offset().top<=$window.scrollTop()+ $window.height();}
function lazyInit(element,func){var $win=jQuery(window);$win.on('load scroll',function(){if((!element.hasClass('lazy-loaded')&&(isScrolledIntoView(element)))){func.call();element.addClass('lazy-loaded');}});}
function attachFormValidator(elements){for(var i=0;i<elements.length;i++){var o=$(elements[i]),v;o.addClass("form-control-has-validation").after("<span class='form-validation'></span>");v=o.parent().find(".form-validation");if(v.is(":last-child")){o.addClass("form-control-last-child");}}
elements.on('input change propertychange blur',function(e){var $this=$(this),results;if(e.type!="blur"){if(!$this.parent().hasClass("has-error")){return;}}
if($this.parents('.rd-mailform').hasClass('success')){return;}
if((results=$this.regula('validate')).length){for(i=0;i<results.length;i++){$this.siblings(".form-validation").text(results[i].message).parent().addClass("has-error")}}else{$this.siblings(".form-validation").text("").parent().removeClass("has-error")}}).regula('bind');}
function isValidated(elements){var results,errors=0;if(elements.length){for(j=0;j<elements.length;j++){var $input=$(elements[j]);if((results=$input.regula('validate')).length){for(k=0;k<results.length;k++){errors++;$input.siblings(".form-validation").text(results[k].message).parent().addClass("has-error");}}else{$input.siblings(".form-validation").text("").parent().removeClass("has-error")}}
return errors==0;}
return true;}
function initBootstrapTooltip(tooltipPlacement){if(window.innerWidth<599){plugins.bootstrapTooltip.tooltip('destroy');plugins.bootstrapTooltip.tooltip({placement:'bottom'});}else{plugins.bootstrapTooltip.tooltip('destroy');plugins.bootstrapTooltip.tooltipPlacement;plugins.bootstrapTooltip.tooltip();}}
var o=$("#copyright-year");if(o.length){o.text(initialDate.getFullYear());}
if(isIE){if(isIE<10){$html.addClass("lt-ie-10");}
if(isIE<11){if(plugins.pointerEvents){$.getScript(plugins.pointerEvents).done(function(){$html.addClass("ie-10");PointerEventsPolyfill.initialize({});});}}
if(isIE===11){$("html").addClass("ie-11");}
if(isIE===12){$("html").addClass("ie-edge");}}
if(plugins.bootstrapTooltip.length){var tooltipPlacement=plugins.bootstrapTooltip.attr('data-placement');initBootstrapTooltip(tooltipPlacement);$(window).on('resize orientationchange',function(){initBootstrapTooltip(tooltipPlacement);})}
if(plugins.bootstrapModalDialog.length>0){var i=0;for(i=0;i<plugins.bootstrapModalDialog.length;i++){var modalItem=$(plugins.bootstrapModalDialog[i]);modalItem.on('hidden.bs.modal',$.proxy(function(){var activeModal=$(this),rdVideoInside=activeModal.find('video'),youTubeVideoInside=activeModal.find('iframe');if(rdVideoInside.length){rdVideoInside[0].pause();}
if(youTubeVideoInside.length){var videoUrl=youTubeVideoInside.attr('src');youTubeVideoInside.attr('src','').attr('src',videoUrl);}},modalItem))}}
if(plugins.rdGoogleMaps.length){var i;$.getScript("//maps.google.com/maps/api/js?key=AIzaSyAFeB0kVA6ouyJ_gEvFbMaefLy3cBCyRwo&sensor=false&libraries=geometry,places&v=3.7",function(){var head=document.getElementsByTagName('head')[0],insertBefore=head.insertBefore;head.insertBefore=function(newElement,referenceElement){if(newElement.href&&newElement.href.indexOf('//fonts.googleapis.com/css?family=Roboto')!=-1||newElement.innerHTML.indexOf('gm-style')!=-1){return;}
insertBefore.call(head,newElement,referenceElement);};function initGoogleMap(){var $this=$(this),styles=$this.attr("data-styles");$this.googleMap({styles:styles?JSON.parse(styles):[],onInit:function(map){var inputAddress=$('#rd-google-map-address');if(inputAddress.length){var input=inputAddress;var geocoder=new google.maps.Geocoder();var marker=new google.maps.Marker({map:map,icon:"images/gmap_marker.png",});var autocomplete=new google.maps.places.Autocomplete(inputAddress[0]);autocomplete.bindTo('bounds',map);inputAddress.attr('placeholder','');inputAddress.on('change',function(){$("#rd-google-map-address-submit").trigger('click');});inputAddress.on('keydown',function(e){if(e.keyCode==13){$("#rd-google-map-address-submit").trigger('click');}});$("#rd-google-map-address-submit").on('click',function(e){e.preventDefault();var address=input.val();geocoder.geocode({'address':address},function(results,status){if(status==google.maps.GeocoderStatus.OK){var latitude=results[0].geometry.location.lat();var longitude=results[0].geometry.location.lng();map.setCenter(new google.maps.LatLng(parseFloat(latitude),parseFloat(longitude)));marker.setPosition(new google.maps.LatLng(parseFloat(latitude),parseFloat(longitude)))}});});}}});}
for(i=0;i<plugins.rdGoogleMaps.length;i++){initGoogleMap.bind(plugins.rdGoogleMaps[i])();}});}
if(plugins.radio.length){var i;for(i=0;i<plugins.radio.length;i++){var $this=$(plugins.radio[i]);$this.addClass("radio-custom").after("<span class='radio-custom-dummy'></span>")}}
if(plugins.checkbox.length){var i;for(i=0;i<plugins.checkbox.length;i++){var $this=$(plugins.checkbox[i]);$this.addClass("checkbox-custom").after("<span class='checkbox-custom-dummy'></span>")}}
if(plugins.popover.length){if(window.innerWidth<767){plugins.popover.attr('data-placement','bottom');plugins.popover.popover();}
else{plugins.popover.popover();}}
if(plugins.statefulButton.length){$(plugins.statefulButton).on('click',function(){var statefulButtonLoading=$(this).button('loading');setTimeout(function(){statefulButtonLoading.button('reset')},2000);})}
if(plugins.rdNavbar.length){plugins.rdNavbar.RDNavbar({stickUpClone:(plugins.rdNavbar.attr("data-stick-up-clone"))?plugins.rdNavbar.attr("data-stick-up-clone")==='true':false});if(plugins.rdNavbar.attr("data-body-class")){document.body.className+=' '+ plugins.rdNavbar.attr("data-body-class");}}
if(plugins.viewAnimate.length){var i;for(i=0;i<plugins.viewAnimate.length;i++){var $view=$(plugins.viewAnimate[i]).not('.active');$document.on("scroll",$.proxy(function(){if(isScrolledIntoView(this)){this.addClass("active");}},$view)).trigger("scroll");}}
if(plugins.owl.length){var i;for(i=0;i<plugins.owl.length;i++){var c=$(plugins.owl[i]),responsive={};var aliaces=["-","-xs-","-sm-","-md-","-lg-"],values=[0,480,768,992,1200],j,k;for(j=0;j<values.length;j++){responsive[values[j]]={};for(k=j;k>=-1;k--){if(!responsive[values[j]]["items"]&&c.attr("data"+ aliaces[k]+"items")){responsive[values[j]]["items"]=k<0?1:parseInt(c.attr("data"+ aliaces[k]+"items"));}
if(!responsive[values[j]]["stagePadding"]&&responsive[values[j]]["stagePadding"]!==0&&c.attr("data"+ aliaces[k]+"stage-padding")){responsive[values[j]]["stagePadding"]=k<0?0:parseInt(c.attr("data"+ aliaces[k]+"stage-padding"));}
if(!responsive[values[j]]["margin"]&&responsive[values[j]]["margin"]!==0&&c.attr("data"+ aliaces[k]+"margin")){responsive[values[j]]["margin"]=k<0?30:parseInt(c.attr("data"+ aliaces[k]+"margin"));}}}
if(c.attr('data-dots-custom')){c.on("initialized.owl.carousel",function(event){var carousel=$(event.currentTarget),customPag=$(carousel.attr("data-dots-custom")),active=0;if(carousel.attr('data-active')){active=parseInt(carousel.attr('data-active'));}
carousel.trigger('to.owl.carousel',[active,300,true]);customPag.find("[data-owl-item='"+ active+"']").addClass("active");customPag.find("[data-owl-item]").on('click',function(e){e.preventDefault();carousel.trigger('to.owl.carousel',[parseInt(this.getAttribute("data-owl-item")),300,true]);});carousel.on("translate.owl.carousel",function(event){customPag.find(".active").removeClass("active");customPag.find("[data-owl-item='"+ event.item.index+"']").addClass("active")});});}
if(typeof(c.attr("data-numbering"))!=='undefined'){var numberingObject=$(c.attr("data-numbering"));c.on('initialized.owl.carousel changed.owl.carousel',function(numberingObject){return function(e){if(!e.namespace)return;numberingObject.find('.numbering-current').text(e.item.index+ 1);numberingObject.find('.numbering-count').text(e.item.count);};}(numberingObject));}
c.owlCarousel({autoplay:c.attr("data-autoplay")==="true",loop:c.attr("data-loop")=='true',items:1,dotsContainer:c.attr("data-pagination-class")||false,navContainer:c.attr("data-navigation-class")||false,mouseDrag:c.attr("data-mouse-drag")!=="false",nav:c.attr("data-nav")==="true",dots:c.attr("data-dots")==="true",dotsEach:c.attr("data-dots-each")?parseInt(c.attr("data-dots-each")):false,animateIn:c.attr('data-animation-in')?c.attr('data-animation-in'):'slide',animateOut:c.attr('data-animation-out')?c.attr('data-animation-out'):false,responsive:responsive,navText:[]});}}
if(plugins.isotope.length){var i,isogroup=[];for(i=0;i<plugins.isotope.length;i++){var isotopeItem=plugins.isotope[i],iso=new Isotope(isotopeItem,{itemSelector:'.isotope-item',layoutMode:isotopeItem.getAttribute('data-isotope-layout')?isotopeItem.getAttribute('data-isotope-layout'):'masonry',filter:'*'});isogroup.push(iso);}
$(window).on('load',function(){setTimeout(function(){var i;for(i=0;i<isogroup.length;i++){isogroup[i].element.className+=" isotope--loaded";isogroup[i].layout();}},600);});var resizeTimout;$("[data-isotope-filter]").on("click",function(e){e.preventDefault();var filter=$(this);clearTimeout(resizeTimout);filter.parents(".isotope-filters").find('.active').removeClass("active");filter.addClass("active");var iso=$('.isotope[data-isotope-group="'+ this.getAttribute("data-isotope-group")+'"]');iso.isotope({itemSelector:'.isotope-item',layoutMode:iso.attr('data-isotope-layout')?iso.attr('data-isotope-layout'):'masonry',filter:this.getAttribute("data-isotope-filter")=='*'?'*':'[data-filter*="'+ this.getAttribute("data-isotope-filter")+'"]'});}).eq(0).trigger("click")}
if(isDesktop&&$html.hasClass("wow-animation")&&$(".wow").length){new WOW().init();}
if(plugins.bootstrapTabs.length){var i;for(i=0;i<plugins.bootstrapTabs.length;i++){var bootstrapTabsItem=$(plugins.bootstrapTabs[i]);bootstrapTabsItem.on("click","a",function(event){event.preventDefault();$(this).tab('show');});}}
if(plugins.rdInputLabel.length){plugins.rdInputLabel.RDInputLabel();}
if(plugins.regula.length){attachFormValidator(plugins.regula);}
if(plugins.rdMailForm.length){var i,j,k,msg={'MF000':'Successfully sent!','MF001':'Recipients are not set!','MF002':'Form will not work locally!','MF003':'Please, define email field in your form!','MF004':'Please, define type of your form!','MF254':'Something went wrong with PHPMailer!','MF255':'Aw, snap! Something went wrong.'};for(i=0;i<plugins.rdMailForm.length;i++){var $form=$(plugins.rdMailForm[i]);$form.attr('novalidate','novalidate').ajaxForm({data:{"form-type":$form.attr("data-form-type")||"contact","counter":i},beforeSubmit:function(){var form=$(plugins.rdMailForm[this.extraData.counter]);var inputs=form.find("[data-constraints]");if(isValidated(inputs)){var output=$("#"+ form.attr("data-form-output"));if(output.hasClass("snackbars")){output.html('<p><span class="icon text-middle fa fa-circle-o-notch fa-spin icon-xxs"></span><span>Sending</span></p>');output.addClass("active");}}else{return false;}},error:function(result){var output=$("#"+ $(plugins.rdMailForm[this.extraData.counter]).attr("data-form-output"));output.text(msg[result]);},success:function(result){var form=$(plugins.rdMailForm[this.extraData.counter]),output=$("#"+ form.attr("data-form-output")),$select=form.find('select'),redirect=form.attr('data-success-redirect');if($select.length){for(j=0;j<$select.length;j++){var $selectitem=$($select[j]);$selectitem.select2('val',null);}}
form.addClass('success');result=result.length==5?result:'MF255';output.text(msg[result]);if(result==="MF000"){if(redirect){setTimeout(function(){window.location.href=redirect;},1000);}
if(output.hasClass("snackbars")){output.html('<p><span class="icon text-middle fa fa-check icon-xxs"></span><span>'+ msg[result]+'</span></p>');}
output.addClass("success active");}else{if(output.hasClass("snackbars")){output.html(' <p class="snackbars-left"><span class="icon icon-xxs fa fa-exclamation-triangle text-middle"></span><span>'+ msg[result]+'</span></p>');}
output.addClass("error active");}
form.clearForm();form.find('input, textarea').blur();setTimeout(function(){output.removeClass("active error success");form.removeClass('success');},5000);}});}}
if(plugins.photoSwipeGallery.length){$document.delegate("[data-photo-swipe-item]","click",function(event){event.preventDefault();var $el=$(this),$galleryItems=$el.parents("[data-photo-swipe-gallery]").find("a[data-photo-swipe-item]"),pswpElement=document.querySelectorAll('.pswp')[0],encounteredItems={},pswpItems=[],options,pswpIndex=0,pswp;if($galleryItems.length==0){$galleryItems=$el;}
$galleryItems.each(function(){var $item=$(this),src=$item.attr('href'),size=$item.attr('data-size').split('x'),pswdItem;if($item.is(':visible')){if(!encounteredItems[src]){pswdItem={src:src,w:parseInt(size[0],10),h:parseInt(size[1],10),el:$item};encounteredItems[src]={item:pswdItem,index:pswpIndex};pswpItems.push(pswdItem);pswpIndex++;}}});options={index:encounteredItems[$el.attr('href')].index,getThumbBoundsFn:function(index){var $el=pswpItems[index].el,offset=$el.offset();return{x:offset.left,y:offset.top,w:$el.width()};}};pswp=new PhotoSwipe(pswpElement,PhotoSwipeUI_Default,pswpItems,options);pswp.init();});}
if(plugins.customToggle.length){var i;for(i=0;i<plugins.customToggle.length;i++){var $this=$(plugins.customToggle[i]);$this.on('click',$.proxy(function(event){event.preventDefault();var $ctx=$(this);$($ctx.attr('data-custom-toggle')).add(this).toggleClass('active');},$this));if($this.attr("data-custom-toggle-disable-on-blur")==="true"){$("body").on("click",$this,function(e){if(e.target!==e.data[0]&&$(e.data.attr('data-custom-toggle')).find($(e.target)).length&&e.data.find($(e.target)).length==0){$(e.data.attr('data-custom-toggle')).add(e.data[0]).removeClass('active');}})}
if($this.attr("data-custom-toggle-hide-on-blur")==="true"){$("body").on("click",$this,function(e){if(e.target!==e.data[0]&&$(e.data.attr('data-custom-toggle')).find($(e.target)).length==0&&e.data.find($(e.target)).length==0){$(e.data.attr('data-custom-toggle')).add(e.data[0]).removeClass('active');}})}}}
if(perspectiveMenu.length){var nav=$('.rd-navbar-wrap'),perspective=$('#perspective');$('#perspective-open-menu').on('click',function(){nav.addClass('active');perspective.addClass('active modalView');});$('#perspective-content-overlay').on('click',function(){nav.removeClass('active');perspective.removeClass('active');setTimeout(function(){perspective.removeClass('modalView');},400);});}
$('#wrapper').scroll(function(){var scroll=$('#wrapper').scrollTop();if(scroll>=76){$('.page-header').addClass("stuck-page-header");}else{$('.page-header').removeClass("stuck-page-header");}});if(plugins.counter.length){var i;for(i=0;i<plugins.counter.length;i++){var $counterNotAnimated=$(plugins.counter[i]).not('.animated');$document.on("scroll",$.proxy(function(){var $this=this;if((!$this.hasClass("animated"))&&(isScrolledIntoView($this))){$this.countTo({refreshInterval:40,speed:$this.attr("data-speed")||1000});$this.addClass('animated');}},$counterNotAnimated)).trigger("scroll");}}
if(plugins.progressBar.length){var i,bar,type;for(i=0;i<plugins.progressBar.length;i++){var progressItem=plugins.progressBar[i];bar=null;if(progressItem.className.indexOf("progress-bar-horizontal")>-1){type='Line';}
if(progressItem.className.indexOf("progress-bar-radial")>-1){type='Circle';}
if(progressItem.getAttribute("data-stroke")&&progressItem.getAttribute("data-value")&&type){bar=new ProgressBar[type](progressItem,{strokeWidth:Math.round(parseFloat(progressItem.getAttribute("data-stroke"))/ progressItem.offsetWidth * 100),
trailWidth:progressItem.getAttribute("data-trail")?Math.round(parseFloat(progressItem.getAttribute("data-trail"))/ progressItem.offsetWidth * 100) : 0,
text:{value:progressItem.getAttribute("data-counter")==="true"?'0':null,className:'progress-bar__body',style:null}});bar.svg.setAttribute('preserveAspectRatio',"none meet");if(type==='Line'){bar.svg.setAttribute(null,"height",progressItem.getAttribute("data-stroke"));}
bar.path.removeAttribute("stroke");bar.path.className.baseVal="progress-bar__stroke";if(bar.trail){bar.trail.removeAttribute("stroke");bar.trail.className.baseVal="progress-bar__trail";}
if(progressItem.getAttribute("data-easing")&&!isIE){$(document).on("scroll",{"barItem":bar},$.proxy(function(event){var bar=event.data.barItem;var $this=$(this);if(this.className.indexOf("progress-bar--animated")===-1){this.className+=" progress-bar--animated";bar.animate(parseInt($this.attr("data-value"))/ 100.0, {
easing:$this.attr("data-easing"),duration:$this.attr("data-duration")?parseInt($this.attr("data-duration")):800,step:function(state,b){if(!b){if(b._container.className.indexOf("progress-bar-horizontal")>-1||b._container.className.indexOf("progress-bar-vertical")>-1){b.text.style.width=Math.abs(b.value()*100).toFixed(0)+"%"}
b.setText(Math.abs(b.value()*100).toFixed(0));}}});}},progressItem)).trigger("scroll");}else{bar.set(parseInt($(progressItem).attr("data-value"))/ 100.0);
bar.setText($(progressItem).attr("data-value"));if(type==='Line'){bar.text.style.width=parseInt($(progressItem).attr("data-value"))+"%";}}}else{console.error(progressItem.className+": progress bar type is not defined");}}}
if(plugins.selectFilter.length){var i;for(i=0;i<plugins.selectFilter.length;i++){var select=$(plugins.selectFilter[i]);select.select2({theme:select.attr('data-custom-theme')?select.attr('data-custom-theme'):"bootstrap"}).next().addClass(select.attr("class").match(/(input-sm)|(input-lg)|($)/i).toString().replace(new RegExp(",",'g')," "));}}
if(plugins.slick.length){var i;for(i=0;i<plugins.slick.length;i++){var $slickItem=$(plugins.slick[i]);$slickItem.slick({slidesToScroll:parseInt($slickItem.attr('data-slide-to-scroll'))||1,asNavFor:$slickItem.attr('data-for')||false,dots:$slickItem.attr("data-dots")=="true",infinite:$slickItem.attr("data-loop")=="true",focusOnSelect:true,arrows:$slickItem.attr("data-arrows")=="true",swipe:$slickItem.attr("data-swipe")=="true",autoplay:$slickItem.attr("data-autoplay")=="true",vertical:$slickItem.attr("data-vertical")=="true",centerMode:$slickItem.attr("data-center-mode")=="true",centerPadding:$slickItem.attr("data-center-padding")?$slickItem.attr("data-center-padding"):'0.50',mobileFirst:true,responsive:[{breakpoint:0,settings:{slidesToShow:parseInt($slickItem.attr('data-items'))||1,}},{breakpoint:479,settings:{slidesToShow:parseInt($slickItem.attr('data-xs-items'))||1,}},{breakpoint:767,settings:{slidesToShow:parseInt($slickItem.attr('data-sm-items'))||1,}},{breakpoint:991,settings:{slidesToShow:parseInt($slickItem.attr('data-md-items'))||1,}},{breakpoint:1199,settings:{slidesToShow:parseInt($slickItem.attr('data-lg-items'))||1,swipe:false}}]}).on('afterChange',function(event,slick,currentSlide,nextSlide){var $this=$(this),childCarousel=$this.attr('data-child');if(childCarousel){$(childCarousel+' .slick-slide').removeClass('slick-current');$(childCarousel+' .slick-slide').eq(currentSlide).addClass('slick-current');}});}}
if(plugins.stepper.length){plugins.stepper.stepper({labels:{up:"",down:""}});}
if(plugins.materialTabs.length){var i;for(i=0;i<plugins.materialTabs.length;i++){var materialTabsItem=plugins.materialTabs[i],responsive={},c=$(materialTabsItem);var aliaces=["-","-xs-","-sm-","-md-","-lg-"],values=[0,480,768,992,1200],j,k;for(j=0;j<values.length;j++){responsive[values[j]]={};for(k=j;k>=-1;k--){if(!responsive[values[j]]["items"]&&c.attr("data"+ aliaces[k]+"items")){responsive[values[j]]["items"]=k<0?1:parseInt(c.attr("data"+ aliaces[k]+"items"));}
if(!responsive[values[j]]["stagePadding"]&&responsive[values[j]]["stagePadding"]!==0&&c.attr("data"+ aliaces[k]+"stage-padding")){responsive[values[j]]["stagePadding"]=k<0?0:parseInt(c.attr("data"+ aliaces[k]+"stage-padding"));}
if(!responsive[values[j]]["margin"]&&responsive[values[j]]["margin"]!==0&&c.attr("data"+ aliaces[k]+"margin")){responsive[values[j]]["margin"]=k<0?30:parseInt(c.attr("data"+ aliaces[k]+"margin"));}}}
$(materialTabsItem).RDMaterialTabs({responsive:responsive,dragContent:true,speed:800});}}});